### ISSUE TITLE
Wrong working directory

### ISSUE THREAD

**Issue by stephanos** [versoul/gulp-data-uri#2]
For some reason the plugin doesn't use the correct working directory (would expect it to be the directory of the source CSS file):

```
[gulp] gulp-data-uri: file not found and it is passed (/Users/.../myapp/node_modules/gulp-load-pluginschevron-left-white.svg)
```

This is my call:

``` javascript
gulp.src("/assets/icons-src/icons.css")
    .pipe(data_uri())
    .pipe(gulp.dest("/assets/icons/icons.css")
```

And this is the CSS:

``` css
.icon-chevron-left-white {
    background-image: url('chevron-left-white.svg');
    background-repeat: no-repeat;
}
```
